#!/bin/sh
set -xe
which docker
docker build \
    --progress=plain \
    --network=host \
    -t musescore4_jack:latest \
    --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) \
    -f Dockerfile \
    .
